### ISSUE TITLE
 'CheckingClient' object has no attribute 'logout'

### ISSUE THREAD

**Issue by fnvm** [sergree/DolboNet#22]
Пытаюсь запустить:
ERROR discord.client Ignoring exception in on_ready 
Traceback (most recent call last): 
File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 377, in _run_event await coro(*args, **kwargs) 
File "C:\Users\user\Desktop\DolboNet-master\core\checking_client.py", line 13, in on_ready await self.logout() 
AttributeError: 'CheckingClient' object has no attribute 'logout'

**Comment by sergree** [comment]
Похоже метод в discord.py стал deprecated. Исправлю asap

**Comment by sergree** [comment]
Тем временем можно откатиться на discord.py 1.7.3 как временное решение

**Comment by sergree** [comment]
Исправлено в https://github.com/sergree/DolboNet/commit/9e16f154f24247967c241439a89c7040c0d13087

1) Заново скачайте код бота
2) Включите **Message Content Intent** в настройках аккаунта бота
![Message Content Intent](https://raw.githubusercontent.com/sergree/DolboNet/master/images/bx8pwm8j2njf.png)
3) Пробуйте снова
